import tkinter
win=tkinter.Tk()
win.title('synnefo')
win.geometry('400x400')
win.minsize(100,100)
win.maxsize(600,600)
win.config(background='red')
l1=tkinter.Label(win,text='welcome')
l2=tkinter.Label(win,text='your not a good boy')
l3=tkinter.Label(win,text='your not a bad boy')
# l1.grid(row=0,column=1)
# l2.grid(row=0,column=0)
# l3.grid(row=0,column=2)
l1.pack()
e1=tkinter.Entry(win,background='white',foreground='black')
e1.pack()
b1=tkinter.Button(win,text='submit')
b1.pack()
b2=tkinter.Radiobutton(win,text='sslc')
b2.pack() 

win.mainloop()